### ISSUE TITLE
High dpi 'QHD display' issue?

### ISSUE THREAD

**Issue by VinCaru** [landrix/TPrintPreview-for-Delphi#1]
Great print preview system, well written, thanks for offering it.

Seems to have issues with new **QHD display** on Windows 10 system. Does not get the correct resolution and shows the page at about 1/4 size of a full Letter sized page. May not have to do with W10 but with just the QHD.

Resolution detection or, higher than expected or allowed resolution error?

**Comment by landrix** [comment]
It only works correct, if your project has enabled the High DPI Support project option (manifest)

**Comment by VinCaru** [comment]
Would be nice to have the preview section of this unit handle higher res screen display without requiring major changes to all the other units for high res. monitors. This would allow existing code to run without major revisions. I'm looking into this.

**Comment by VinCaru** [comment]
With the new Windows 10.1 Redstone 1 update TPrintPreview works well as a virtulized Windows form except when the QHD laptop screen is running alone (no external monitor) and not at 100% Display Mode Setting. Strange. This is an improvement in Windows management of Hi Res virtulized screens.

Windows is expected to update early next year with 10.1 Redstone 2 which may fix this. The MS Windows managers interviews I have read indicate more work is planed to handle High Res screens that still have some issues, maybe like this strange scaling error.

When there is an issue the rendered content of the pages are about 75% of what it should be including a box showing the margins.

Will keep working on this new issue that will still be a problem for some users as many laptops with Hi Res screens used without external monitor are not used at 100% because the icons and text are way to small to read.

Thanks.

**Comment by landrix** [comment]
Done
