### ISSUE TITLE
Thumbnails are not working...

### ISSUE THREAD

**Issue by cenitu** [landrix/TPrintPreview-for-Delphi#3]
The TThumbnailPreview is not functioning. They are not working in the Demos either. When I use the Demos from DelphiArea the thumbnails are showing as expected. But when opening DelphiArea projects the IDE (10.3) raises error that TThumbnail class is not available. When I pass two error messages with cancel (if I click ignore the declarations are dissapearing) the form does not show. Only code shows but it is working normally. Also I did not understand the implementation code of TThumbnailPreview from this demo.

**Comment by landrix** [comment]
fixed
