### ISSUE TITLE
dsPDF Conditional compilation not working

### ISSUE THREAD

**Issue by AndrewKED** [landrix/TPrintPreview-for-Delphi#4]
There appears to be a bug with Delphi {$ELSEIF}, and {$ELSE} with a following {$IFDEF} and closing {$ENDIF} must be used.  PageNo must be defined in var in SaveAsPDF for PDF_DSPDF compilations.

(I am not quite git-savvy enough to make these changes and push)

**Comment by landrix** [comment]
fixed
